name: CI

on:
  pull_request:
    paths:
      - "api/**.js"
      - "api/**eslint**"
      - "api/package-lock.json"
      - ".github/workflows/lint-api.yml"
jobs:
  lint-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2-beta

      # lint api
      - run: |
          npm ci
          npm run lint
        working-directory: ./api
