name: CI

on:
  pull_request:
    paths:
      - "**.vue"
      - "frontend/**.ts"
      - "frontend/**eslint**"
      - "frontend/package-lock.json"
      - ".github/workflows/lint-frontend.yml"
jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2-beta

      # lint frontend
      - run: |
          npm ci
          npm run lint
        working-directory: ./frontend
