name: CI

on:
  pull_request:
    paths:
      - "**.js"
      - "**.ts"
      - "**eslint**"
      - "package.json"
      - Dockerfile
      - ".github/workflows/lint.yml"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      # lint Dockerfile
      - uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # lint Makefile
      # Get and build checkmake
      - uses: actions/checkout@v2
        with:
          repository: mrtazz/checkmake
          path: checkmake
          ref: 0.1.0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
        id: go
      # https://github.com/mrtazz/checkmake/blob/1383019b4b84bf8af0a50f8d186f067d64720c12/.github/workflows/ci.yml#L21
      - run: |
          sudo wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
          sudo dpkg -i pandoc-2.7.3-1-amd64.deb
          make
          chmod +x checkmake
          ./checkmake --version
          ./checkmake ../Makefile
        working-directory: ./checkmake

      # lint api
      - run: |
          npm ci
          npm run lint
        working-directory: ./api

      # lint frontend
      - run: |
          npm ci
          npm run lint
        working-directory: ./frontend
