name: CI

on:
  pull_request:
    paths:
      - "**.js"
      - "**.ts"
      - "**eslint**"
      - "package.json"
      - Dockerfile
      - Makefile
      - ".github/workflows/lint.yml"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      # lint Dockerfile
      - uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # lint Makefile
      # Get and build checkmake
      - uses: actions/checkout@v2
        with:
          repository: mrtazz/checkmake
          path: checkmake
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - name: Build checkmake
        run: |
          sudo wget https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
          sudo dpkg -i pandoc-2.9.2.1-1-amd64.deb
          make
          chmod +x checkmake
          ./checkmake --version
        working-directory: ./checkmake

      - run: ./checkmake/checkmake Makefile

      # lint api
      - run: |
          npm ci
          npm run lint
        working-directory: ./api

      # lint frontend
      - run: |
          npm ci
          npm run lint
        working-directory: ./frontend
