name: Test

on:
  pull_request:
    paths:
      - "**.vue"
      - "frontend/**.ts"
      - "frontend/**eslint**"
      - "frontend/package-lock.json"
      - ".github/workflows/test-frontend.yml"

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ">=14.4"

      - run: npm ci
        working-directory: ./frontend

      - run: npm test -- --coverage --colors --ci
        working-directory: ./frontend

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./frontend/coverage/coverage-final.json
          flags: frontend
          fail_ci_if_error: true
