name: CI

on:
  pull_request:
    paths:
      - "api/**.js"
      - "api/**eslint**"
      - "api/package-lock.json"
      - ".github/workflows/test-api.yml"
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2-beta

      - run: |
          npm ci
          npm test
        working-directory: ./api

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./api/coverage/coverage-final.json
          flags: api
          fail_ci_if_error: true
