name: Test

on:
  pull_request:
    paths:
      - "api/**.js"
      - "api/package-lock.json"
      - ".github/workflows/test-api.yml"
jobs:
  api:
    runs-on: ubuntu-latest
    services:
      mongod:
        image: mongo:latest
        ports:
          - 27017:27017
    env:
      JWT_SECRET: jwt_super_secret_1
      MONGOHQ_URL: mongodb://localhost/paypay-challenge-test

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ">=14.4"

      - name: Init database
        run: mongo $(basename $MONGOHQ_URL) init-db.js

      - run: npm ci
        working-directory: ./api

      - run: npm test
        working-directory: ./api

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./api/coverage/coverage-final.json
          flags: api
          fail_ci_if_error: true
